const users = [
    {
      firstname: "John",
      lastname: "Doe",
      email: "johndoe@gmail.com",
      designation: "Financial Division HOD",
      department: "Finance",
      phone: "1234567890",
      address: "123, ABC Street, XYZ City, 123456",
      gender: "Male",
      profilePic: "https://www.w3schools.com/howto/img_avatar.png",
    },
    {
      firstname: "Jane",
      lastname: "Doe",
      email: "janedoe@gmail.com",
      designation: "Marketing Division HOD",
      department: "Marketing",
      phone: "0987654321",
      address: "456, DEF Street, UVW City, 654321",
      gender: "Female",
      profilePic: "https://www.w3schools.com/howto/img_avatar.png",
    },
    {
      firstname: "Tom",
      lastname: "Smith",
      email: "tomsmith@gmail.com",
      designation: "HR Division HOD",
      department: "Human Resources",
      phone: "6789054321",
      address: "789, GHI Street, RST City, 954321",
      gender: "Male",
      profilePic: "https://www.w3schools.com/howto/img_avatar.png",
    },
    {
      firstname: "Emily",
      lastname: "Johnson",
      email: "emilyjohnson@gmail.com",
      designation: "IT Division HOD",
      department: "Information Technology",
      phone: "3216549870",
      address: "246, JKL Street, MNO City, 987032",
      gender: "Female",
      profilePic: "https://www.w3schools.com/howto/img_avatar.png",
    },
    {
      firstname: "Michael",
      lastname: "Williams",
      email: "michaelwilliams@gmail.com",
      designation: "Operations Division HOD",
      department: "Operations",
      phone: "1357902468",
      address: "369, PQR Street, STU City, 246813",
      gender: "Male",
      profilePic: "https://www.w3schools.com/howto/img_avatar.png",
    },
    {
      firstname: "Sophie",
      lastname: "Brown",
      email: "sophiebrown@gmail.com",
      designation: "Sales Division HOD",
      department: "Sales",
      phone: "2468135790",
      address: "159, VWX Street, YZA City, 357809",
      gender: "Female",
      profilePic: "https://www.w3schools.com/howto/img_avatar.png",
    }
  ];
  